Udacity course 


In [290]:
#Softmax function 

In [291]:
import numpy as np
x = np.arange(-2,6,.1) ##similiar to linspace 
score  = np.vstack([x, np.ones_like(x), .2*np.ones_like(x)])  ##stacks the array vetically



In [292]:
score

array([[ -2.00000000e+00,  -1.90000000e+00,  -1.80000000e+00,
         -1.70000000e+00,  -1.60000000e+00,  -1.50000000e+00,
         -1.40000000e+00,  -1.30000000e+00,  -1.20000000e+00,
         -1.10000000e+00,  -1.00000000e+00,  -9.00000000e-01,
         -8.00000000e-01,  -7.00000000e-01,  -6.00000000e-01,
         -5.00000000e-01,  -4.00000000e-01,  -3.00000000e-01,
         -2.00000000e-01,  -1.00000000e-01,   1.77635684e-15,
          1.00000000e-01,   2.00000000e-01,   3.00000000e-01,
          4.00000000e-01,   5.00000000e-01,   6.00000000e-01,
          7.00000000e-01,   8.00000000e-01,   9.00000000e-01,
          1.00000000e+00,   1.10000000e+00,   1.20000000e+00,
          1.30000000e+00,   1.40000000e+00,   1.50000000e+00,
          1.60000000e+00,   1.70000000e+00,   1.80000000e+00,
          1.90000000e+00,   2.00000000e+00,   2.10000000e+00,
          2.20000000e+00,   2.30000000e+00,   2.40000000e+00,
          2.50000000e+00,   2.60000000e+00,   2.70000000e+00,
        

softmax func--> generates a prb for the clases labels provided--> *10 /10 has differetn affects on the prb

Hot code --> converts the number into bianary
if you have too many classes one hot encoding can get a littel messy --> embeding comes in handy tho


In [293]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [294]:
# Load the library with the iris dataset
from sklearn.datasets import load_iris

# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Load pandas
import pandas as pd

# Load numpy
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [295]:
Location = r'/Users/akash/Desktop/context_time_taken.csv'
df = pd.read_csv(Location)


In [296]:
df = pd.read_csv(Location, header=0)


In [297]:
X = df[['context_meta_id','time','date','day']]
X_arr = pd.DataFrame.as_matrix(X).ravel()
X = np.array(X)
X
X.shape

(276, 4)

In [298]:
y = df[['late_ontime']]
y_arr = pd.DataFrame.as_matrix(y).ravel()

In [299]:
y_arr.shape


(276,)

In [300]:
X_arr.shape

(1104,)

In [301]:
clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2).fit(X, y_arr)
clf2 = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)
clf3 = ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)

In [302]:
X_test = X[275 :]
X_test
y_test = y_arr[275 :]
y_test

array([0])

In [305]:
scores = cross_val_score(clf, X, y_arr)
scores2 = cross_val_score(clf2, X, y_arr)
scores3 = cross_val_score(clf3, X, y_arr)

scores.mean()
clf.fit(X, y_arr)
clf.predict(X_test)

array([0])

In [306]:
scores2.mean()


0.89597942964001875

In [307]:
clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()
eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
    scores = cross_val_score(clf, X, y_arr, cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))


Accuracy: 0.90 (+/- 0.13) [Logistic Regression]
Accuracy: 0.90 (+/- 0.13) [Random Forest]
Accuracy: 0.90 (+/- 0.13) [naive Bayes]
Accuracy: 0.90 (+/- 0.13) [Ensemble]


In [308]:
from sklearn import datasets
iris = datasets.load_iris()
X, y = iris.data[:, 1:3], iris.target
X.shape

(150, 2)

In [309]:
clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()
eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
    scores = cross_val_score(clf, X, y, cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))


Accuracy: 0.90 (+/- 0.05) [Logistic Regression]
Accuracy: 0.93 (+/- 0.05) [Random Forest]
Accuracy: 0.91 (+/- 0.04) [naive Bayes]
Accuracy: 0.95 (+/- 0.05) [Ensemble]


In [310]:
#  Copyright 2016 The TensorFlow Authors. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""DNNRegressor with custom input_fn for Housing dataset."""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import itertools

import pandas as pd
import tensorflow as tf

tf.logging.set_verbosity(tf.logging.INFO)

In [311]:

COLUMNS = ["context_meta_id", "time", "date", "day"]
FEATURES = ["context_meta_id", "date", "day"]
LABEL = "time"

In [312]:
FEATURES

['context_meta_id', 'date', 'day']

In [313]:
 
  # Feature cols
 
def input_fn(data_set):
  feature_cols = {k: tf.constant(data_set[k].values) for k in FEATURES}
  labels = tf.constant(data_set[LABEL].values)
  return feature_cols, labels  



In [315]:

# Load datasets
training_set = pd.read_csv("boston_train.csv", skipinitialspace=True,
                         skiprows=1, names=COLUMNS)
test_set = pd.read_csv("boston_test.csv", skipinitialspace=True,
                     skiprows=1, names=COLUMNS)
# Set of 6 examples for which to predict median house values
prediction_set = pd.read_csv("boston_predict.csv", skipinitialspace=True,
                               skiprows=1, names=COLUMNS)



In [316]:
feature_cols = [tf.contrib.layers.real_valued_column(k)
                  for k in FEATURES]


In [317]:
# Build 2 layer fully connected DNN with 10, 10 units respectively.
regressor = tf.contrib.learn.DNNRegressor(feature_columns=feature_cols,
                                        hidden_units=[4, 4],
                                        model_dir="/tmp/context_model")


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x11298e630>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/context_model'}


In [318]:
# Fit
regressor.fit(input_fn=lambda: input_fn(training_set), steps=5000)


Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables_1/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "/Users/akash/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)', 'File "/Users/akash/anaconda/lib/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)', 'File "/Users/akash/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py", line

INFO:tensorflow:global_step/sec: 1139.11
INFO:tensorflow:loss = 1.51447, step = 5501 (0.088 sec)
INFO:tensorflow:global_step/sec: 1044.77
INFO:tensorflow:loss = 1.51447, step = 5601 (0.096 sec)
INFO:tensorflow:global_step/sec: 1183.23
INFO:tensorflow:loss = 1.51446, step = 5701 (0.085 sec)
INFO:tensorflow:global_step/sec: 1217.73
INFO:tensorflow:loss = 1.51446, step = 5801 (0.082 sec)
INFO:tensorflow:global_step/sec: 1134.51
INFO:tensorflow:loss = 1.51445, step = 5901 (0.088 sec)
INFO:tensorflow:global_step/sec: 1065.76
INFO:tensorflow:loss = 1.51445, step = 6001 (0.094 sec)
INFO:tensorflow:global_step/sec: 1080.19
INFO:tensorflow:loss = 1.51444, step = 6101 (0.092 sec)
INFO:tensorflow:global_step/sec: 1105.62
INFO:tensorflow:loss = 1.51444, step = 6201 (0.090 sec)
INFO:tensorflow:global_step/sec: 1187.55
INFO:tensorflow:loss = 1.51444, step = 6301 (0.085 sec)
INFO:tensorflow:global_step/sec: 1128.59
INFO:tensorflow:loss = 1.51443, step = 6401 (0.088 sec)
INFO:tensorflow:global_step/se

DNNRegressor(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._RegressionHead object at 0x11298e358>, 'hidden_units': [4, 4], 'feature_columns': (_RealValuedColumn(column_name='context_meta_id', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='date', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='day', dimension=1, default_value=None, dtype=tf.float32, normalizer=None)), 'optimizer': None, 'activation_fn': <function relu at 0x11d0f9730>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [319]:

# Score accuracy
ev = regressor.evaluate(input_fn=lambda: input_fn(test_set), steps=1)
loss_score = ev["loss"]
print("Loss: {0:f}".format(loss_score))

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-07-25-14:06:39
INFO:tensorflow:Restoring parameters from /tmp/context_model/model.ckpt-10000
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2017-07-25-14:06:39
INFO:tensorflow:Saving dict for global step 10000: global_step = 10000, loss = 1.51428
Loss: 1.514280


In [320]:
# Print out predictions
y = regressor.predict(input_fn=lambda: input_fn(prediction_set))
# .predict() returns an iterator; convert to a list and print predictions
predictions = list(itertools.islice(y, 6))
print("Predictions: {}".format(str(predictions)))



Instructions for updating:
Please switch to predict_scores, or set `outputs` argument.
INFO:tensorflow:Restoring parameters from /tmp/context_model/model.ckpt-10000
Predictions: [2.1677291, 2.1605532, 2.1533787, 2.1511774, 2.2111738, 2.2139492]
